// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using currency_api.Data;

#nullable disable

namespace currency_api.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    [Migration("20240708105657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("currency_api.Models.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChineseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currency", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            ChineseName = "美元"
                        },
                        new
                        {
                            Code = "GBP",
                            ChineseName = "英鎊"
                        },
                        new
                        {
                            Code = "EUR",
                            ChineseName = "歐元"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
